FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "path-exclude /usr/share/man/*" >> /etc/dpkg/dpkg.cfg.d/excludes && \
    echo "path-exclude /usr/share/doc/*" >> /etc/dpkg/dpkg.cfg.d/excludes && \
    echo "path-exclude /usr/share/locale/*" >> /etc/dpkg/dpkg.cfg.d/excludes && \
    apt update && \
    apt install -y --no-install-recommends \
      build-essential \
      curl \
      git ccache \
      ca-certificates && \
    apt clean && \
    curl -L -o premake.tar.gz https://github.com/danielga/garrysmod_common/releases/download/premake-build%2F5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && \
    tar -xvf premake.tar.gz --directory=/usr/bin && \
    rm -f premake.tar.gz && \
    gcc --version && \
    strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX && \
    rm -rf /var/lib/apt/lists/* /usr/share/* /usr/sbin/* /var/cache/* /var/log/* /var/tmp/* /var/lib/dpkg/info/*

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/bin/bash"]