FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "path-exclude /usr/share/man/*" >> /etc/dpkg/dpkg.cfg.d/excludes && \
    echo "path-exclude /usr/share/doc/*" >> /etc/dpkg/dpkg.cfg.d/excludes && \
    echo "path-exclude /usr/share/locale/*" >> /etc/dpkg/dpkg.cfg.d/excludes

RUN apt update && \
    apt install -y --no-install-recommends \
      build-essential \
      curl \
      git ccache \
      ca-certificates && \
    apt clean && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/bin/bash"]