name: Build

on: 
  push:
    paths:
      - '.github/workflows/compile.yml'
      - 'source/**'
      - 'libs/**'
      - 'premake5.lua'
      - '!source/public/README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "template"
      BUILD_64x: "true"
      REALM: "sv"